spring:
  datasource:
    driver-class-name: org.postgresql.Driver
    url: jdbc:postgresql://${dev-db.postgres.host}:${dev-db.postgres.port}/${dev-db.postgres.name}
    username: ${dev-db.postgres.username}
    password: ${dev-db.postgres.password}
    hikari:
      auto-commit: false

  jpa:
    properties:
      hibernate:
        hbm2ddl.auto: update
    open-in-view: false

api:
  url: http://54.180.99.46:8080

chatbot:
  api-url: http://13.124.164.168:5000/get-response
