spring:
  datasource:
    driver-class-name: org.postgresql.Driver
    url: jdbc:postgresql://${local-db.postgres.host}:${local-db.postgres.port}/${local-db.postgres.name}
    username: ${local-db.postgres.username}
    password: ${local-db.postgres.password}
    hikari:
      auto-commit: false
  
  jpa:
    properties:
      hibernate:
        format_sql: true
        highlight_sql: true
        hbm2ddl.auto: create
        query.fail_on_pagination_over_collection_fetch: true
    open-in-view: false
    show-sql: true

api:
  url: http://localhost:8080

logging:
  level:
    org.springframework.jdbc: debug
    org.springframework.web.cors.DefaultCorsProcessor: trace
    org.hibernate.orm.jdbc.bind: trace
    org.springframework.transaction.interceptor: trace

chatbot:
  api-url: http://localhost:5000/get-response
