positions:
  filename: /tmp/positions.yaml

clients:
  - url: http://host.docker.internal:3100/loki/api/v1/push

scrape_configs:
  - job_name: log
    static_configs:
      - targets:
          - localhost
        labels:
          job: was_logs
          __path__: /logs/file.log
