version: '3.7'
services:
  prometheus:
    image: prom/prometheus
    container_name: prometheus
    ports:
      - 9090:9090
    volumes:
      - ./prometheus/config:/etc/prometheus
      - ./prometheus/volume:/prometheus
    command:
      - '--web.enable-lifecycle'
      - '--config.file=/etc/prometheus/prometheus.yml'
    restart: always
    networks:
      - promnet

  grafana:
    image: grafana/grafana
    container_name: grafana
    ports:
      - 3000:3000
    volumes:
      - ./grafana/volume:/var/lib/grafana
    restart: always
    networks:
      - promnet

  loki:
    image: grafana/loki
    container_name: loki
    ports:
      - 3100:3100
    volumes:
      - ./loki/config:/etc/loki
      - ./loki/data:/loki
    command:
      - '--config.file=/etc/loki/loki-config.yml'
    restart: always
    networks:
      - promnet

networks:
  promnet:
    driver: bridge
